export const LABELMAP: { [key: string]: any } = {
  directors: "Directors",
  officerOfCorporations: "Office of Corporation",
  businessActivity: "Business Activity",
  province: "Province",
  address: "Address",
  city: "City",
  postalCode: "Postal Code",
  apartment: "Appartment",

  firstName: "First Name",
  middleName: "Middle Name",
  lastName: "Last Name",
  designation: "Designation",
  phone: "Phone",
  email: "Email",
  suite: "Suite",
  residencyStatus: "Residency Status",
  name: "Name",
  ocn: "OCN",
  articleOfIncorporation: "Article of Incorporation",
  rights: "Rights",
  restriction: "Restriction",
  otherProvisions: "Other Provisions",
  intentionOfCorporation: "Intention of corporation",

  initialSharePrice: "Initial Share Price",
  priceOfClassAvotingShare: "Price of Class A Voting Share",
  priceOfClassBnonVotingShare: "Price of Class B Non Voting Share",
  numOfClassShare: "Number of Class Share",

  class: "Share Class",
  preference: "Share Preference",
  votingRights: "Voting Rights",
  initialPrice: "Initial Price",

  priceOfAShare: "Price of A Share",
  priceOfBShare: "Price of B Share",
  priceOfPerShare: "Price of Per Share",
  customArticleText: "Custom Article Text",
  customArticleAttachment: "Custom Article Attachment",
  shareholderOfCorporation: "Shareholder of Corporation",
  shareClass: "Share Class",
  numberOfShare: "Number of Share",

  gstHstReg: "GST/HST Registration",
  payrollReg: "Payroll Registration",
  importExportReg: "Import/Export Registration",
  dividendAccReg: "Dividend Account Registration",
  initialReturn: "Initial Return",
  wsib: "WSIB",
  domainReg: "Domain Registration",
  emailReg: "Email Registration",
  corporateSeal: "Corporate Seal",
  PhysicalMinuteBook: "Physical minute book",
  oneYearServiceSupport: "One year service support",
  annualReturn: "Annual Return"
};
